services:
  - type: web
    name: gestion-compte-om
    env: docker
    dockerfilePath: Dockerfile
    plan: starter
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ballast.proxy.rlwy.net:29955/railway
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: HXzcpVHHSOuCxCmsxKfmkbFbbjaFFcPI

# Pas besoin de cr√©er une base Render ici, donc on supprime la section "databases"
