server:
  port: 8080

spring:
  application:
    name: GestionCompteOM

  datasource:
    url: jdbc:postgresql://ballast.proxy.rlwy.net:29955/railway
    username: postgres
    password: HXzcpVHHSOuCxCmsxKfmkbFbbjaFFcPI
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # (create, update, none, validate)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: messages  # <-- Pour charger ton fichier message.yaml
    encoding: UTF-8

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
